# Generated by Django 5.1.3 on 2024-12-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_digitalproduct_userdigitalpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalproduct',
            name='stream_url',
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='s3_object_key',
            field=models.CharField(default='placeholder/object-key.mp4', help_text='S3 object key for the digital content', max_length=255),
            preserve_default=False,
        ),
    ]
