# Generated by Django 5.1.3 on 2025-01-20 13:53

import ecommerce.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=ecommerce.storage_backends.ImageStorage(), upload_to='upload/products/'),
        ),
    ]
