# Generated by Django 5.1.3 on 2024-12-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_shippingaddress_invoice_shippingaddress_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
